package org.pacos.plugin.kafka.view.message;
import com.vaadin.flow.component.button.Button; import com.vaadin.flow.component.combobox.ComboBox; import com.vaadin.flow.component.orderedlayout.HorizontalLayout; import com.vaadin.flow.component.orderedlayout.VerticalLayout; import com.vaadin.flow.component.textfield.TextArea; import com.vaadin.flow.component.textfield.TextField; import com.vaadin.flow.data.binder.Binder; import org.pacos.plugin.kafka.backend.connection.*; import org.pacos.plugin.kafka.backend.message.*; import java.util.*; import java.util.function.Consumer;
public class KafkaMessageForm<T extends KafkaMessageDraft> {
 private final KafkaConnectionService connections; private final KafkaMessageService messages; private final Class<T> type; private ComboBox<Long> connection; private ComboBox<KafkaMessageTemplate> template; private Binder<T> binder;
 public KafkaMessageForm(KafkaConnectionService connections,KafkaMessageService messages,Class<T> type){this.connections=connections;this.messages=messages;this.type=type;}
 public Binder<T> create(VerticalLayout layout,List<org.vaadin.addons.variablefield.data.Scope> scopes){
  binder=new Binder<>(type); connection=new ComboBox<>("Kafka connection"); connection.setItems(connections.findAll().stream().map(KafkaConnection::getId).toList()); connection.setItemLabelGenerator(id->connections.find(id).map(KafkaConnection::getName).orElse("#"+id));
  TextField topic=new TextField("Topic"); topic.setWidthFull(); TextField key=new TextField("Key (optional)"); key.setWidthFull(); TextArea payload=new TextArea("Payload"); payload.setWidthFull(); payload.setMinHeight("180px");
  template=new ComboBox<>("Saved message configuration"); template.setItems(messages.templates()); template.setItemLabelGenerator(KafkaMessageTemplate::getName); Button load=new Button("Load",e->{KafkaMessageTemplate t=template.getValue();if(t!=null){T bean=newBean();bean.setConnectionId(t.getConnection().getId());bean.setTopic(t.getTopic());bean.setMessageKey(t.getMessageKey());bean.setPayload(t.getPayload());binder.readBean(bean);}});
  binder.forField(connection).asRequired("Connection is required").bind(KafkaMessageDraft::getConnectionId,KafkaMessageDraft::setConnectionId); binder.forField(topic).asRequired("Topic is required").bind(KafkaMessageDraft::getTopic,KafkaMessageDraft::setTopic); binder.forField(key).bind(KafkaMessageDraft::getMessageKey,KafkaMessageDraft::setMessageKey); binder.forField(payload).asRequired("Payload is required").bind(KafkaMessageDraft::getPayload,KafkaMessageDraft::setPayload);
  layout.add(new HorizontalLayout(template,load),connection,topic,key,payload); return binder;
 }
 public T newBean(){try{return type.getDeclaredConstructor().newInstance();}catch(Exception e){throw new IllegalStateException(e);}}
 public ComboBox<KafkaMessageTemplate> templateSelector(){return template;}
 public void refreshTemplates(){if(template!=null)template.setItems(messages.templates());}
 public KafkaMessageTemplate toTemplate(String name,T bean){KafkaMessageTemplate t=new KafkaMessageTemplate();t.setName(name);t.setConnection(connections.find(bean.getConnectionId()).orElseThrow());t.setTopic(bean.getTopic());t.setMessageKey(bean.getMessageKey());t.setPayload(bean.getPayload());return t;}
 public void bind(T bean){binder.readBean(bean);} public T write()throws Exception{T bean=newBean();binder.writeBean(bean);return bean;}
}