package org.pacos.plugin.kafka.view.connection;
import com.vaadin.flow.component.button.Button; import com.vaadin.flow.component.combobox.ComboBox; import com.vaadin.flow.component.grid.Grid; import com.vaadin.flow.component.notification.Notification; import com.vaadin.flow.component.orderedlayout.HorizontalLayout; import com.vaadin.flow.component.orderedlayout.VerticalLayout; import com.vaadin.flow.component.textfield.TextArea; import com.vaadin.flow.component.textfield.PasswordField; import com.vaadin.flow.component.textfield.TextField; import org.pacos.plugin.kafka.backend.connection.KafkaConnection; import org.pacos.plugin.kafka.backend.connection.KafkaConnectionService; import java.util.*;
public class KafkaConnectionView extends VerticalLayout {
 private final KafkaConnectionService service; private final Grid<KafkaConnection> grid=new Grid<>(KafkaConnection.class,false); private final TextField name=new TextField("Name"); private final TextField bootstrap=new TextField("Bootstrap servers"); private final ComboBox<String> protocol=new ComboBox<>("Security protocol"); private final ComboBox<String> mechanism=new ComboBox<>("SASL mechanism"); private final TextField username=new TextField("Username"); private final PasswordField password=new PasswordField("Password"); private final TextArea additional=new TextArea("Additional Kafka properties (key=value, one per line)"); private KafkaConnection selected;
 public KafkaConnectionView(KafkaConnectionService service){this.service=service;setSizeFull(); protocol.setItems("PLAINTEXT","SSL","SASL_PLAINTEXT","SASL_SSL"); mechanism.setItems("PLAIN","SCRAM-SHA-256","SCRAM-SHA-512"); bootstrap.setWidthFull(); additional.setWidthFull(); additional.setMinHeight("120px"); grid.addColumn(KafkaConnection::getName).setHeader("Name");grid.addColumn(KafkaConnection::getBootstrapServers).setHeader("Bootstrap servers");grid.addColumn(KafkaConnection::getSecurityProtocol).setHeader("Protocol");grid.setHeight("220px");grid.addItemClickListener(e->load(e.getItem()));
 Button save=new Button("Save",e->save());Button test=new Button("Test connection",e->test());Button delete=new Button("Delete",e->delete());Button clear=new Button("New",e->clear()); HorizontalLayout actions=new HorizontalLayout(clear,save,test,delete);add(grid,name,bootstrap,protocol,mechanism,username,password,additional,actions);refresh();}
 private void load(KafkaConnection c){selected=c;name.setValue(c.getName());bootstrap.setValue(c.getBootstrapServers());protocol.setValue(Optional.ofNullable(c.getSecurityProtocol()).orElse("PLAINTEXT"));mechanism.setValue(c.getSaslMechanism());username.setValue(Optional.ofNullable(c.getUsername()).orElse(""));password.setValue(Optional.ofNullable(c.getPassword()).orElse(""));additional.setValue(Optional.ofNullable(c.getAdditionalProperties()).orElse(""));}
 private KafkaConnection bean(){KafkaConnection c=selected==null?new KafkaConnection():selected;c.setName(name.getValue());c.setBootstrapServers(bootstrap.getValue());c.setSecurityProtocol(protocol.getValue());c.setSaslMechanism(mechanism.getValue());c.setUsername(username.getValue());c.setPassword(password.getValue());c.setAdditionalProperties(additional.getValue());return c;}
 private void save(){try{selected=service.save(bean());refresh();Notification.show("Kafka connection saved");}catch(Exception e){Notification.show("Save failed: "+e.getMessage());}}
 private void test(){try{service.test(bean());Notification.show("Kafka connection OK");}catch(Exception e){Notification.show("Connection failed: "+e.getMessage());}}
 private void delete(){if(selected!=null){service.delete(selected.getId());clear();refresh();Notification.show("Kafka connection deleted");}}
 private void clear(){selected=null;name.clear();bootstrap.clear();protocol.setValue("PLAINTEXT");mechanism.clear();username.clear();password.clear();additional.clear();}
 private void refresh(){grid.setItems(service.findAll());}
}