create table kafka_connection (
    id bigint generated by default as identity primary key,
    name varchar(200) not null,
    bootstrap_servers varchar(2000) not null,
    security_protocol varchar(40) not null,
    sasl_mechanism varchar(80),
    username varchar(500),
    password varchar(2000),
    additional_properties varchar(10000),
    created_at timestamp default current_timestamp not null,
    updated_at timestamp default current_timestamp not null,
    constraint uk_kafka_connection_name unique (name)
);

create table kafka_message_template (
    id bigint generated by default as identity primary key,
    name varchar(200) not null,
    connection_id bigint not null,
    topic varchar(1000) not null,
    message_key varchar(4000),
    payload clob not null,
    created_at timestamp default current_timestamp not null,
    updated_at timestamp default current_timestamp not null,
    constraint fk_kafka_template_connection foreign key (connection_id) references kafka_connection(id),
    constraint uk_kafka_template_name unique (name)
);